### ISSUE TITLE
Image not shown via URI

### ISSUE THREAD

**Issue by feriyusuf** [vivchar/RendererRecyclerViewAdapter#23] opened 2018-09-12 17:41 UTC
Here is my code

`mRecyclerViewAdapter.registerRenderer(new ViewBinder<>(R.layout.item_list_produk, Produk.class, (model, finder, payloads) -> finder .setText(R.id.item_product_name, model.getNamaProduk()) .setText(R.id.item_product_price, getResources().getString(R.string.txt_caption_selected_money).concat(" ") .concat(String.valueOf(model.getHarga()))) .setText(R.id.item_product_durability,  String.valueOf(model.getKetahanan()).concat(" ") .concat(getResources().getString(R.string.txt_caption_hours_durability))) .setText(R.id.item_product_uom, model.getSatuan().concat(" ") .concat(getString(R.string.txt_caption_product_uom))) .setOnClickListener(new View.OnClickListener() { @Override public void onClick(View v) { mActivity.showDetail(model); } }).setImageURI(R.id.item_list_produk_image, "http://www.example.com/image.jpg") ));`

**Comment by vivchar** [comment] 2018-09-13 19:09
1 Please format your code
2 It is not a bug of my library, you should use https://stackoverflow.com
3 Read the documentation [setImageURI](https://developer.android.com/reference/android/widget/ImageView#setImageURI(android.net.Uri))
4 You should use Glide or Picasso

closing

**Closed as completed by vivchar** 2018-09-13 19:09 UTC
